### PR TITLE
pass correct variable to class

### PR DESCRIPTION
**Pull request by andrewtwemlow**
inccorect value is being used to determine whcih crontab entry to create

### CODE REVIEW

**Comment by kekogya** [comment]
@twem I will take a look.

**Review by kekogya — APPROVED** [review]
@twem Thanks for catching that and submitting a pull request. I will publish the update to the forge soon.

**Comment by andrewtwemlow** [comment]
Thanks, can you also please take a look at 

https://github.com/indiana-university/puppet-aide/issues/4
Let me know if you want me to create a PR for the change

**Comment by kekogya** [comment]
> Thanks, can you also please take a look at
> 
> #4
> Let me know if you want me to create a PR for the change

I have commented on that. Let me know what your thoughts are on those comments.

**Comment by kekogya** [comment]
The latest module has been posted to the forge.

**Pull request merged**
